name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        config:
        - { name: "GCC", cc: gcc, cxx: g++ }
        - { name: "clang", cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          sudo apt-get install -qq libsdl2-dev libfreetype6 ninja-build
          pip3 install meson
      - name: Build package
        run: bash build-packages.sh x86-64
      - name: upload packages
        uses: actions/upload-artifact@v2
        with:
          name: Ubuntu Package
          path: lite-xl-linux-*.tar.gz

  build-macox:
    name: Build Mac OS X
    runs-on: macos-10.15
    strategy:
      matrix:
        config:
        # - { name: "GCC", cc: gcc-10, cxx: g++-10 }
        - { name: "clang", cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install meson
          brew install ninja sdl2
      - name: Build package
        run: bash build-packages.sh x86-64
      - name: upload packages
        uses: actions/upload-artifact@v2
        with:
          name: Mac OS X Package
          path: lite-xl-macosx-*.zip
